### ISSUE TITLE
🐛 [BUG] - Page Not Found after clicking on slack logo

### ISSUE THREAD

**Issue by jjshanks** [opentofu/opentofu.org#192]
### Description

When clicking on the slack logo from the home page it gives a `Page Not Found` error. Discussed in slack https://opentofucommunity.slack.com/archives/C05QF5HA0BH/p1697328997314189

### Reproduction steps

```bash
1. Go to https://opentofu.org/
2. Click on slack icon
3. See error
```

### Screenshots
![Screenshot 2023-10-14 171511](https://github.com/opentofu/opentofu.org/assets/62661/bcea55af-7ec7-4e5f-8ec9-0db30acb0740)

### Browsers

Chrome

### OS

Windows

**Comment by jjshanks** [comment]
This seems to be a result of #190. Should that PR be reverted till the TODO about using version 3 can be completed?

**Comment by damianstasik** [comment]
@jjshanks thanks for reporting, the fix was implemented, could you verify whether it works correctly on your end?
