### ISSUE TITLE
💡 [IMPROVEMENT] - Allow dev workflow to run on pull requests synchronize events

### ISSUE THREAD

**Issue by Sirivasv** [opentofu/opentofu.org#202]
### Summary

When a pull request gets a new commit the dev workflow doesn't trigger.

### Basic Example

https://github.com/opentofu/opentofu.org/pull/197

### Drawbacks

none

**Comment by Roma36** [comment]
related issue: 
https://github.com/opentofu/opentofu.org/issues/205
