### ISSUE TITLE
🐛 [BUG] - Slack link no longer active

### ISSUE THREAD

**Issue by a-nldisr** [opentofu/opentofu.org#215]
### Description

Slack link on the main page is no longer active for invites. 

### Reproduction steps

```bash
After clicking the link:
https://opentofu.org/slack

For the Slack community on page: 
https://opentofu.org/

I got this notification: 
![image](https://github.com/opentofu/opentofu.org/assets/1867776/734f4023-59ed-4253-a3f1-9ca4800bb85c)


The link is no longer active.
```

### Screenshots

```bash
![image](https://github.com/opentofu/opentofu.org/assets/1867776/734f4023-59ed-4253-a3f1-9ca4800bb85c)
```

### Browsers

Chrome

### OS

Mac

**Comment by cube2222** [comment]
Thanks, will update!

Unfortunately, I think the link stops being active after a certain number of people use it (it has no expiration).

**Comment by cube2222** [comment]
Should be working now, thanks again!
