### ISSUE TITLE
🐛 [BUG] - Tables in docs formatting is broken.

### ISSUE THREAD

**Issue by cube2222** [opentofu/opentofu.org#224]
### Description

The first column is mis-formatted in all docs tables

Most likely a CSS issue.

### Reproduction steps

e.g. here https://opentofu.org/docs/language/syntax/json

### Browsers

Chrome, Safari

### OS

Mac

**Comment by cube2222** [comment]
Couldn't add the screenshot through the form, so here it is:

<img width="982" alt="Screenshot 2023-11-29 at 11 50 22" src="https://github.com/opentofu/opentofu.org/assets/7013055/6be13718-589a-47af-9c6f-7f59c21a066c">

**Comment by janosdebugs** [comment]
Could also be a formatting issue in the Markdown. This seems to work for me:

```
| Col | Col |
|:----|-----|
| ...   | ...    |
```

**Comment by janosdebugs** [comment]
Thanks @vtrenton , I have the CSS-related issues on my todo list for the holidays if nobody picks it up until then.

**Comment by janosdebugs** [comment]
Thanks for the debugging @vtrenton ! Keep it coming if you find anything, this will make writing a fix much easier.
