### ISSUE TITLE
💡 [IMPROVEMENT] - add RSS feed for the blog

### ISSUE THREAD

**Issue by Yantrio** [opentofu/opentofu.org#229]
### Summary

Help discoverability

### Basic Example

-

### Drawbacks

-

**Comment by skyzyx** [comment]
I went to subscribe to the blog so that I can follow it, and there was no feed! 😱

Would love to be able to subscribe to the blog!

**Comment by damianstasik** [comment]
The RSS feed seems to be generated by default:
https://opentofu.org/blog/rss.xml

**Comment by janosdebugs** [comment]
We should still link it in the HTML header.

**Comment by virtualroot** [comment]
@janosdebugs I do see it in the HTML header.

```
<link rel="alternate" type="application/rss+xml" href="/blog/rss.xml" title="OpenTofu RSS Feed">
<link rel="alternate" type="application/atom+xml" href="/blog/atom.xml" title="OpenTofu Atom Feed">
```

**Comment by janosdebugs** [comment]
Thanks @virtualroot I guess that's it then!

**Comment by skyzyx** [comment]
I see it showing up on https://opentofu.org, but not https://opentofu.org/blog. :)

**Comment by virtualroot** [comment]
> I see it showing up on [opentofu.org](https://opentofu.org), but not [opentofu.org/blog](https://opentofu.org/blog). :)

I can't reproduce this issue with [Brook](https://addons.mozilla.org/en-US/firefox/addon/brook-feed-reader/).
Also, the W3C Feed Validation service has no problems reaching the RSS with [opentofu.org/blog](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fopentofu.org%2Fblog%2F).
