### ISSUE TITLE
💡 [IMPROVEMENT] - This website should use Google's Noto font

### ISSUE THREAD

**Issue by stillinbeta** [opentofu/opentofu.org#263]
### Summary

[It'd be really funny](https://fonts.google.com/noto)

### Basic Example

body {
  font-family: Noto
}

### Drawbacks

Probably none

**Comment by janosdebugs** [comment]
Hey @stillinbeta it took me a while to get it, good one. ;) However, as we do not have any international content (yet?), this is currently not a priority. I'm going to close the issue.
