### ISSUE TITLE
🐛 [BUG] - Slack invitation link expired

### ISSUE THREAD

**Issue by patrickdung** [opentofu/opentofu.org#269]
### Description

Please update the Slack invitation settings in the opentofu.org

https://opentofu.org/slack/

### Reproduction steps

```bash
https://opentofu.org/slack/
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Firefox

### OS

Windows

**Comment by Yantrio** [comment]
Hi, Thanks for reporting this, we fixed this in #271
